# Generated by Django 5.1.15 on 2026-05-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0063_taskassignment_rejection_reason_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskassignment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskassignment",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
