'use client';

import { DashboardLayout } from '@/components/layout/dashboard-layout';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Upload, X, Plus, Save, Eye, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import Image from 'next/image';
import React from 'react';
import CourseBasicInfo from './course-basic-info';
import CourseSettings from './course-settings';
import CoursePricing from './course-pricing';
import { COURSE_CATEGORIES, COURSE_LEVELS } from '@/lib/constants';
import { useMutation } from '@tanstack/react-query';
import { CreateCourseAction } from '@/app/admin/course/create/_actions';
import { TCourse, TCourseInsert, TCourseInsertSchema } from '@/drizzle/schema';
import { toast } from 'sonner';
import { useForm, FormProvider } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';

export default function CourseForm() {
  const [courseImage, setCourseImage] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [previewMode, setPreviewMode] = useState(false);

  const methods = useForm<TCourseInsert>({
    resolver: zodResolver(TCourseInsertSchema),
    defaultValues: {
      title: '',
      courseDuration: '',
      description: '',
      courseCategory: 'web_development',
      difficultyLevel: 'beginner',
      subTitle: '',
      prerequisites: '',
      coursePrice: 0,
      thumbnailUrl: '',
      courseLanguage: 'english',
      instructorId: '', // This should be set from your auth context
      id: '', // This will be generated by the backend
    },
  });

  const { mutate: createCourse, isPending } = useMutation({
    mutationFn: CreateCourseAction,
    onSuccess: () => {
      toast.success('Course created successfully');
      methods.reset(); // Reset form after successful creation
      // You might want to navigate to the courses list here
    },
    onError: (error: Error) => {
      toast.error('Failed to create course: ' + error.message);
    },
  });

  const onSubmit = methods.handleSubmit((data) => {
    const courseData: TCourseInsert = {
      ...data,
      thumbnailUrl: courseImage,
      // Add any additional fields needed
    };
    createCourse(courseData);
  };

  return (
    <FormProvider {...methods}>
      <form onSubmit={onSubmit}>
        <div className='top-0 sticky flex justify-between items-center bg-background my-2 px-2 py-4 border-b'>
          <div className='flex items-center space-x-4'>
            <div>
              <h1 className='font-bold text-3xl'>Create New Course</h1>
              <p className='text-muted-foreground'>
                Build an engaging learning experience for your students
              </p>
            </div>
          </div>
          <div className='flex items-center space-x-2'>
            <Button type="button" variant='outline'>
              <Eye className='mr-2 w-4 h-4' />
              {previewMode ? "Edit" : "Preview"}
            </Button>
            <Button type="button" variant='outline' onClick={() => methods.reset()}>
              <Save className='mr-2 w-4 h-4' />
              Save Draft
            </Button>
            <Button type="submit" disabled={isPending}>
              {isPending ? 'Publishing...' : 'Publish Course'}
            </Button>
          </div>
        </div>
        <Tabs defaultValue='basic' className='bg-background py-3'>
          <TabsList className='mb-4'>
            <TabsTrigger value='basic'>Basic Information</TabsTrigger>
            <TabsTrigger value='settings'>Settings</TabsTrigger>
            <TabsTrigger value='pricing'>Pricing</TabsTrigger>
          </TabsList>
          <TabsContent value='basic' className='space-y-6'>
            <CourseBasicInfo
              courseImage={courseImage}
              setCourseImage={setCourseImage}
              selectedTags={selectedTags}
              setSelectedTags={setSelectedTags}
            />
          </TabsContent>
          <TabsContent value='settings'>
            <CourseSettings />
          </TabsContent>
          <TabsContent value='pricing'>
            <CoursePricing />
          </TabsContent>
        </Tabs>
      </form>
    </FormProvider>
    </div>
  );
}
