# Generated by Django 5.1.15 on 2026-05-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_organizationmember_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("annotator", "Annotator"),
                    ("reviewer", "Reviewer"),
                ],
                default="annotator",
                help_text="Role of the member in the organization",
                max_length=20,
            ),
        ),
    ]
