# Generated by Django 5.1.15 on 2026-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_alter_organizationmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="If True, all users under this organization lose access to the platform.",
                verbose_name="is suspended",
            ),
        ),
    ]
