# Generated by Django 5.1.15 on 2026-05-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_organization_is_suspended"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="If True, this individual member loses access; the rest of the organization is unaffected.",
            ),
        ),
    ]
